openapi: 3.0.1
info:
  title: Store3d API
  description: This is an Store3d API document
  contact:
    email: info@store3d.om
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://store3d-api.example.com/store3d/api/v1
- url: /store3d/api/v1
security:
- basicAuth: []
- JWT: []
tags:
- name: user
  description: Operations about user

paths:
  /users/:
    get:
      tags:
      - user
      summary: Get All Users
      description: This can only be done by the logged in user.
      operationId: GetUsers
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: per_page
          schema:
            type: integer
          description: items per page
        - in: query
          name: sort
          schema:
            type: string
          description: sort field
        - in: query
          name: sort_order
          schema:
            type: string
            enum:
              - asc
              - desc
          description: order
        - in: query
          name: queries
          schema:
            type: array
            items:
              type: string
          description: field,operator,value _exp_ | name,eq,mazoman&email,eq,info@mazoman.com|, opernation| eq,ne,lt,gt,le,ge,like |
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  filter:
                      $ref: '#/components/schemas/filter'
        401:
          $ref: '#/components/responses/Unauthorized'

  /users/my:
    get:
      tags:
      - user
      summary: Get My User
      description: This can only be done by the logged in user.
      operationId: GetMyUser
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
  
  /users/image:
    post:
      tags:
      - user
      summary: Add user id image
      description: This can only be done by the logged in user.
      operationId: AddMyImage
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_card_image:
                    type: string
                    format: binary

        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
  /users/image/{userId}:
    post:
      tags:
      - user
      summary: Add user id image
      description: This can only be done by the logged in user.
      operationId: AddUserImageByID
      parameters:
      - name: userId
        in: path
        description: The id that needs to be updated
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_card_image:
                    type: string
                    format: binary

        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
  /users/search/{param}:
    get:
      tags:
      - user
      summary: Search Users
      description: This can only be done by the logged in user.
      operationId: SearchUsers
      parameters:
      - name: param
        in: path
        description: The search param
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
          
  /users/{userId}:
    get:
      tags:
      - user
      summary: Get User
      description: This can only be done by the logged in user.
      operationId: GetUser
      parameters:
        - in: path
          name: userId
          schema:
            type: string
            format: uuid
          required: true
          description: The id of the user
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
      - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
      - name: userId
        in: path
        description: The id that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
  /users/disable/{userId}:
    patch:
      tags:
      - user
      summary: Disable user
      description: This can only be done by the logged in user.
      operationId: disableUser
      parameters:
      - name: userId
        in: path
        description: The id that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
  /users/{user_id}/password:
    post:
      tags:
      - user
      summary: Update user password
      description: This can only be done by the logged in user.
      operationId: UpdateUserPassword
      parameters:
      - name: user_id
        in: path
        description: The id that needs to be updated
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  format: password
      responses:
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'

  
  /users/type/{user_type}:
    get:
      tags:
      - user
      summary: Get All Users by type
      description: This can only be done by the logged in user.
      operationId: GetUsersByType
      parameters:
      - name: user_type
        in: path
        description: The user type
        required: true
        schema:
          type: string
          enum:
            - USER
            - ADMIN
            - OWNER
            - GOVERNMENT
            - CORPORATE
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
  

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        is_active:
          type: boolean
        phone:
          type: integer
        email:
          type: string
          format: email
        user_type:
          type: string
          enum:
            - USER
            - ADMIN
            - OWNER
            - GOVERNMENT
            - CORPORATE
        id_user:
          type: string
        id_user_image:
          type: string
        
        mobile_confirmed_at:
          type: string
          format: date-time
        email_confirmed_at:
          type: string
          format: date-time
    filter:
      type: object
      properties:
        page:
          type: integer
          format: int64
        per_page:
          type: integer
          format: int64
        sort:
          type: string
        sort_order:
          type: string
          enum:
              - asc
              - desc
        queries:
          type: string
          description: field,operator,value _exp_ | name,eq,mazoman&email,eq,info@mazoman.com|, opernation| eq,ne,lt,gt,le,ge,like |
    Global:
      required:
      #- code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    Error:
      required:
      #- code
      - message
      type: object
      properties:
        #code:
        #  type: string
        message:
          type: string
          example: Authorization information is missing or invalid.
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    JWT:
      type: apiKey
      name: x-access-tokens
      in: header
