openapi: 3.0.1
info:
  title: Store3d API
  description: This is an Store3d API document
  contact:
    email: info@store3d.om
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://store3d-api.example.com/store3d/api/v1
- url: /store3d/api/v1
security:
- basicAuth: []
- JWT: []
tags:
- name: faq
  description: Operations about Templates Content

paths:
  /faqs/:
    get:
      tags:
      - faq
      summary: Get All Faqs
      description: This can only be done by the logged in user.
      operationId: GetFaqs
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  faqs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Faq'
                  filter:
                      $ref: '#/components/schemas/filter'
        401:
          $ref: '#/components/responses/Unauthorized'
    post:
      tags:
      - faq
      summary: Add Faq
      description: This can only be done by the logged in user.
      operationId: AddFaq
      requestBody:
        description: Add faq object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Faq'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'

        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
      x-codegen-request-body-name: body
  /faqs/{id}:
    get:
      tags:
      - faq
      summary: Get faq
      description: This can only be done by the logged in user.
      operationId: getFaqById
      parameters:
      - name: id
        in: path
        description: The id that needs to get
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Faq'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    delete:
      tags:
      - faq
      summary: Delete faq
      description: This can only be done by the logged in user.
      operationId: deleteFaq
      parameters:
      - name: id
        in: path
        description: The id that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    patch:
      tags:
      - faq
      summary: Updated Faq
      description: This can only be done by the logged in user.
      operationId: updateFaq
      parameters:
      - name: id
        in: path
        description: ID that need to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Updated faq object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Faq'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
      x-codegen-request-body-name: body
  /faqs/topics/{id}:
    get:
      tags:
      - faq
      summary: Get faq
      description: This can only be done by the logged in user.
      operationId: getFaqByUserId
      parameters:
      - name: id
        in: path
        description: The id that needs to get
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Faq'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'

  /faqs/topic/:
    get:
      tags:
      - faq
      summary: Get All Faq topics
      description: This can only be done by the logged in user.
      operationId: GetFaqtopics
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  faqs:
                    type: array
                    items:
                      $ref: '#/components/schemas/FaqTopic'
                  filter:
                      $ref: '#/components/schemas/filter'
        401:
          $ref: '#/components/responses/Unauthorized'
    post:
      tags:
      - faq
      summary: Add Faq topic
      description: This can only be done by the logged in user.
      operationId: AddFaqTopic
      requestBody:
        description: Add faq topic object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaqTopic'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'

        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
      x-codegen-request-body-name: body
  /faqs/topic/{id}:
    get:
      tags:
      - faq
      summary: Get faq topic
      description: This can only be done by the logged in user.
      operationId: getFaqTopicById
      parameters:
      - name: id
        in: path
        description: The id that needs to get
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaqTopic'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    delete:
      tags:
      - faq
      summary: Delete faq topic
      description: This can only be done by the logged in user.
      operationId: deleteFaqTopic
      parameters:
      - name: id
        in: path
        description: The id that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    patch:
      tags:
      - faq
      summary: Updated Faq Topic
      description: This can only be done by the logged in user.
      operationId: updateFaqTopic
      parameters:
      - name: id
        in: path
        description: ID that need to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Updated faq topic object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaqTopic'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
      x-codegen-request-body-name: body  

components:
  schemas:
    Faq:
      type: object
      properties:
        id:
          type: string
          format: uuid
        faq_topic_id:
          type: string
          format: uuid
        content:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string
        question:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string
        create_date:
          type: string
          format: date-time
        modified_date:
          type: string
          format: date-time
    FaqTopic:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string
        create_date:
          type: string
          format: date-time
        modified_date:
          type: string
          format: date-time

    filter:
      type: object
      properties:
        page:
          type: integer
          format: int64
        per_page:
          type: integer
          format: int64
        sort:
          type: string
        sort_order:
          type: string
          enum:
              - asc
              - desc
        queries:
          type: string
          description: field,operator,value _exp_ | name,eq,mazoman&email,eq,info@mazoman.com|, opernation| eq,ne,lt,gt,le,ge,like |
    Global:
      required:
      #- code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    Error:
      required:
      #- code
      - message
      type: object
      properties:
        #code:
        #  type: string
        message:
          type: string
          example: Authorization information is missing or invalid.
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    JWT:
      type: apiKey
      name: x-access-tokens
      in: header
