openapi: 3.0.1
info:
  title: Store3d API
  description: This is an Store3d API document
  contact:
    email: info@store3d.om
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://store3d-api.example.com/store3d/api/v1
- url: /store3d/api/v1
security:
- basicAuth: []
- JWT: []
tags:
- name: branch
  description: Operations about Branch

paths:
  /branchs/:
    get:
      tags:
      - branch
      summary: Get All Branchs
      description: This can only be done by the logged in user.
      operationId: GetBranchs
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  branchs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Branch'
        401:
          $ref: '#/components/responses/Unauthorized'
    post:
      tags:
      - branch
      summary: Create branch
      description: This can only be done by the logged in user.
      operationId: CreateBranch
      requestBody:
        description: Create branch object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Store3dtBranch'
        required: true
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
  /branchs/{id}:
    get:
      tags:
      - branch
      summary: Get branch
      description: This can only be done by the logged in user.
      operationId: getBranchById
      parameters:
      - name: id
        in: path
        description: The id that needs to get
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  branchs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Branch'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    delete:
      tags:
      - branch
      summary: Delete branch
      description: This can only be done by the logged in user.
      operationId: delete_branch
      parameters:
      - name: id
        in: path
        description: The id that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    patch:
      tags:
      - branch
      summary: Updated Branch
      description: This can only be done by the logged in user.
      operationId: update_branch
      parameters:
      - name: id
        in: path
        description: ID that need to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Updated branch object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Store3dtBranch'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
  
components:
  schemas:
    Branch:
      type: object
      properties:
        id:
          type: string
          format: uuid
        location:
          type: string
        manager:
          type: string
        name:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string
        create_date:
          type: string
          format: date-time
        modified_date:
          type: string
          format: date-time
    
    Store3dtBranch:
      type: object
      properties:
        location:
          type: string
        manager:
          type: string
        name:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string

    Global:
      required:
      #- code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    Error:
      required:
      #- code
      - message
      type: object
      properties:
        #code:
        #  type: string
        message:
          type: string
          example: Authorization information is missing or invalid.
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    JWT:
      type: apiKey
      name: x-access-tokens
      in: header
