"""create Initial table

Revision ID: 2dea99c6ac9d
Revises: 
Create Date: 2025-09-28 20:47:34.432333

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
import uuid
from depot.fields.sqlalchemy import UploadedFileField

# revision identifiers, used by Alembic.
revision = '2dea99c6ac9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('branch',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('manager', sa.String(length=255), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_create_date'), ['create_date'], unique=False)

    op.create_table('cart',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('company',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('manager', sa.String(length=255), nullable=True),
    sa.Column('cr_number', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=255), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cr_number'),
    sa.UniqueConstraint('tax_id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_create_date'), ['create_date'], unique=False)

    op.create_table('expense_category',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['expense_category.id'], name='fk_expense_category_parent_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_topic',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('model_type', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('delivery_amount', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('customer_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('branch_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('payment_status', sa.Enum('none', 'pending', 'cancel', 'error', 'fail', 'success', 'refund', name='paymentstatusenum'), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=True)

    op.create_table('labor_category',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['labor_category.id'], name='fk_labor_category_parent_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('model_type', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('collection_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('disk', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('order_column', sa.Integer(), nullable=True),
    sa.Column('file', UploadedFileField(), nullable=True),
    sa.Column('custom_properties', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_gateway',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('payment_type',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('payments',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('invoice_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'mobile_payment', 'bank_transfer', name='paymentoptionenum'), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('print_materials',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('PLA', 'ABS', 'PETG', 'TPU', 'WOOD_FILLED', 'METAL_FILLED', 'CARBON_FIBER', 'NYLON', name='printmaterialtypeenum'), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('cost_per_gram', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('density', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('print_temperature', sa.Integer(), nullable=True),
    sa.Column('bed_temperature', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_settings',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quality', sa.Enum('DRAFT', 'STANDARD', 'HIGH', 'ULTRA_HIGH', name='printqualityenum'), nullable=False),
    sa.Column('layer_height', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('infill_percentage', sa.Integer(), nullable=False),
    sa.Column('print_speed', sa.Integer(), nullable=False),
    sa.Column('support_enabled', sa.Boolean(), nullable=True),
    sa.Column('raft_enabled', sa.Boolean(), nullable=True),
    sa.Column('brim_enabled', sa.Boolean(), nullable=True),
    sa.Column('estimated_time_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_packaging',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('KEYCHAIN', 'WRAPPER', 'TAG', 'BOX', 'CUSTOM', name='packagingtypeenum'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('customer_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('branch_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('qoute_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='quotestatusenum'), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_quotation_customer_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name='fk_quotation_branch_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_quotation_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_number'), ['number'], unique=True)

    op.create_table('roles',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('slider_type',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('staff',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('nationality', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id_card_number', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card_number')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_create_date'), ['create_date'], unique=False)

    op.create_table('store',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('manager', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_create_date'), ['create_date'], unique=False)

    op.create_table('supplier',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('vat_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('specializes_in', sa.JSON(), nullable=True),
    sa.Column('material_types', sa.JSON(), nullable=True),
    sa.Column('equipment_types', sa.JSON(), nullable=True),
    sa.Column('service_capabilities', sa.JSON(), nullable=True),
    sa.Column('quality_certifications', sa.JSON(), nullable=True),
    sa.Column('compliance_standards', sa.JSON(), nullable=True),
    sa.Column('minimum_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_title', sa.String(length=100), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('details', sa.UnicodeText(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logo', UploadedFileField(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('last_order_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_supplier_code'), ['supplier_code'], unique=True)

    op.create_table('templates_content',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('media_type', sa.Enum('SMS', 'EMAIL', 'PUSH', name='mediatypeenum'), server_default='sms', nullable=False),
    sa.Column('model_type', sa.String(length=255), nullable=True),
    sa.Column('model_op', sa.String(length=255), nullable=True),
    sa.Column('model_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'media_type', name='_key_media_uc')
    )
    with op.batch_alter_table('templates_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_content_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_content_media_type'), ['media_type'], unique=False)

    op.create_table('user_notification',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notification_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.Enum('ADMIN', 'USER', 'OWNER', 'GOVERNMENT', 'CORPORATE', name='usertypeenum'), server_default='USER', nullable=True),
    sa.Column('language', sa.Enum('ENGLISH', 'ARABIC', name='languageenum'), server_default='ARABIC', nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('user_id_image', UploadedFileField(), nullable=True),
    sa.Column('user_details', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mobile_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('is_agree', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('agree_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('oauth', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('branch_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['branch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('cart_item',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('service_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('service_type', sa.String(length=255), nullable=True),
    sa.Column('cart_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.Column('css_class', sa.String(length=128), nullable=True),
    sa.Column('icon', UploadedFileField(), nullable=True),
    sa.Column('image', UploadedFileField(), nullable=True),
    sa.Column('banner_image', UploadedFileField(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('default_material_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('default_settings_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('min_order_quantity', sa.Integer(), nullable=True),
    sa.Column('max_order_quantity', sa.Integer(), nullable=True),
    sa.Column('base_commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('markup_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_material_id'], ['print_materials.id'], ),
    sa.ForeignKeyConstraint(['default_settings_id'], ['print_settings.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name='fk_category_parent_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_category_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_slug'), ['slug'], unique=True)

    op.create_table('city_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['city.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('company_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('customer',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_registration', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('currency_preference', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('preferred_materials', sa.JSON(), nullable=True),
    sa.Column('quality_preference', sa.String(length=20), nullable=True),
    sa.Column('color_preferences', sa.JSON(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('newsletter_subscription', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('referral_code', sa.String(length=50), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_code'), ['customer_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_mobile'), ['mobile'], unique=False)

    op.create_table('expense_category_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['expense_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('faq',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('faq_topic_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faq_topic_id'], ['faq_topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_topic_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['faq_topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('fiscal_year',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('company_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='fiscalyearstatusenum'), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_fiscal_year_company_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_year_create_date'), ['create_date'], unique=False)

    op.create_table('labor',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('unit', sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR', 'METER', 'METER_SQUARE', 'METER_CUBIC', 'LITER_PER_HOUR', 'LITER', 'KILOGRAM', 'GRAM', 'PIECE', 'BAG', 'BOX', 'BUNDLE', 'CARTON', 'GALLON', 'BARREL', 'DRUM', 'TON', name='laborunitenum'), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='laborstatusenum'), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['labor_category.id'], name='fk_labor_category_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labor_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labor_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_labor_create_date'), ['create_date'], unique=False)

    op.create_table('labor_category_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['labor_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('login_tracking',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('others', sa.String(length=255), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_login_tracking_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_config',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payment_gateway', sa.String(length=255), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('fee_cap', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('limit', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('access_key', sa.String(length=255), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('merchant_key1', sa.String(length=255), nullable=True),
    sa.Column('merchant_key2', sa.String(length=255), nullable=True),
    sa.Column('merchant_key3', sa.String(length=255), nullable=True),
    sa.Column('merchant_key4', sa.String(length=255), nullable=True),
    sa.Column('merchant_key5', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_gateway'], ['payment_gateway.name'], name='fk_payment_config_payment_gateway'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_config_name'), ['name'], unique=True)

    op.create_table('payment_transaction',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('requester', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('payment_status', sa.Enum('none', 'pending', 'cancel', 'error', 'fail', 'success', 'refund', name='paymentstatusenum'), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_status', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('model_type', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('model_action', sa.String(length=255), nullable=True),
    sa.Column('response_code', sa.String(length=255), nullable=True),
    sa.Column('response_decision', sa.String(length=255), nullable=True),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('card_name', sa.String(length=20), nullable=True),
    sa.Column('card_expiry_date', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('retry', sa.Integer(), server_default='0', nullable=True),
    sa.Column('dump_response', sa.Text(), nullable=True),
    sa.Column('custom_properties', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('config_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('payment_gateway', sa.String(length=255), nullable=True),
    sa.Column('payment_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['payment_gateway'], ['payment_gateway.name'], ),
    sa.ForeignKeyConstraint(['payment_type'], ['payment_type.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transaction_gateway_transaction_id'), ['gateway_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_reference_id'), ['reference_id'], unique=True)

    op.create_table('printers',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('build_volume_x', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('build_volume_y', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('build_volume_z', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('layer_resolution', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('nozzle_diameter', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('branch_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('last_maintenance', sa.DateTime(), nullable=True),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('total_print_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('electricity_cost_per_hour', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('role_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('permission_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_permissions_permission_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_role_permissions_role_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('sellers',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('business_license', sa.String(length=100), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=False),
    sa.Column('business_phone', sa.String(length=20), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_routing_number', sa.String(length=20), nullable=True),
    sa.Column('bank_swift_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'SUSPENDED', 'REJECTED', 'INACTIVE', name='sellerstatusenum'), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('commission_type', sa.Enum('PERCENTAGE', 'FIXED', 'TIERED', name='commissiontypeenum'), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_frequency', sa.String(length=20), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_commission_earned', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_commission_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_approve_orders', sa.Boolean(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('shipping_addresses',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_addresses_create_date'), ['create_date'], unique=False)

    op.create_table('slider',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('enable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('slider_type', sa.String(length=255), nullable=False),
    sa.Column('image', UploadedFileField(), nullable=False),
    sa.Column('platform', sa.Enum('MOBILE', 'ANDROID', 'IOS', 'WEB', 'ALL', name='platformenum'), server_default='ALL', nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['slider_type'], ['slider_type.name'], name='fk_slider_slider_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slider_from_date'), ['from_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_slider_to_date'), ['to_date'], unique=False)

    op.create_table('store_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('templates_content_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.Unicode(length=255), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['templates_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('user_roles',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('role_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_roles_role_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_roles_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Item_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['cart_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('category_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('customer_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('expense',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='expensestatusenum'), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('fiscal_year_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], name='fk_expense_category_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_year.id'], name='fk_expense_fiscal_year_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_fiscal_year_id'), ['fiscal_year_id'], unique=False)

    op.create_table('faq_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('question', sa.UnicodeText(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['faq.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('fiscal_period',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('company_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('financial_year_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('period_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='fiscalyearstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_fiscal_period_company_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['fiscal_year.id'], name='fk_fiscal_period_financial_year_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('expected_delivery', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ORDERED', 'RECEIVED', 'CANCELLED', name='orderstatusenum'), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('terms', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('total_print_time_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_material_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_post_processing', sa.Boolean(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('supplier_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_order_supplier_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)

    op.create_table('printer_materials',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('printer_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('material_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('recommended_print_temperature', sa.Integer(), nullable=True),
    sa.Column('recommended_bed_temperature', sa.Integer(), nullable=True),
    sa.Column('recommended_print_speed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['print_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printer_id', 'material_id', name='unique_printer_material')
    )
    op.create_table('product',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('category_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('subcategory_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_dynamic_pricing', sa.Boolean(), nullable=True),
    sa.Column('print_time_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('material_usage_grams', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('print_volume_x', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('print_volume_y', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('print_volume_z', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('layer_height', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('infill_percentage', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.Enum('PIECE', 'KG', 'LITER', 'METER', 'BOX', 'BAG', 'BUNDLE', 'CARTON', 'GALLON', 'BARREL', 'DRUM', 'TON', 'GRAM', 'METER_SQUARE', 'METER_CUBIC', 'LITER_PER_HOUR', name='productunitenum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('is_digital', sa.Boolean(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('model_files', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_digital_download', sa.Boolean(), nullable=True),
    sa.Column('supplier_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_product_category_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['category.id'], name='fk_product_subcategory_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_product_supplier_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_create_date'), ['create_date'], unique=False)

    op.create_table('seller_commissions',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('seller_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('commission_type', sa.Enum('PERCENTAGE', 'FIXED', 'TIERED', name='commissiontypeenum'), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tier_1_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tier_1_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tier_2_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tier_2_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tier_3_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('minimum_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maximum_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('agreement_terms', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_documents',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('seller_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_file', UploadedFileField(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('renewal_reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_payments',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('seller_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_period_start', sa.DateTime(), nullable=False),
    sa.Column('commission_period_end', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='paymentstatusenum'), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_performance',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('seller_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('new_customers', sa.Integer(), nullable=True),
    sa.Column('returning_customers', sa.Integer(), nullable=True),
    sa.Column('customer_retention_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('top_selling_product', sa.String(length=255), nullable=True),
    sa.Column('total_products_sold', sa.Integer(), nullable=True),
    sa.Column('rank_in_period', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slider_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['slider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('inventory',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('branch_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('store_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_alert', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name='fk_inventory_branch_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_inventory_product_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name='fk_inventory_store_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_store_id'), ['store_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('order_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('material_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('settings_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('packaging_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('color_preference', sa.String(length=50), nullable=True),
    sa.Column('finish_type', sa.String(length=50), nullable=True),
    sa.Column('model_file_name', sa.String(length=255), nullable=True),
    sa.Column('model_file_size', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['print_materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packaging_id'], ['product_packaging.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settings_id'], ['print_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('order_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('model_file', UploadedFileField(), nullable=False),
    sa.Column('model_file_name', sa.String(length=255), nullable=False),
    sa.Column('model_file_size', sa.BigInteger(), nullable=False),
    sa.Column('model_file_type', sa.String(length=50), nullable=False),
    sa.Column('material_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('print_settings_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('packaging_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('scale_x', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('scale_y', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('scale_z', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('estimated_print_time', sa.Integer(), nullable=True),
    sa.Column('estimated_material_usage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PREPARING', 'PRINTING', 'POST_PROCESSING', 'QUALITY_CHECK', 'PACKAGING', 'COMPLETED', 'FAILED', 'CANCELLED', name='printjobstatusenum'), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('assigned_printer_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('assigned_user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('quality_approved', sa.Boolean(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('quality_approved_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('quality_approved_at', sa.DateTime(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['print_materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packaging_id'], ['product_packaging.id'], ),
    sa.ForeignKeyConstraint(['print_settings_id'], ['print_settings.id'], ),
    sa.ForeignKeyConstraint(['quality_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_cost_breakdown',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('overhead_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('packaging_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('markup_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_packaging_options',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('packaging_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['packaging_id'], ['product_packaging.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'packaging_id', name='unique_product_packaging')
    )
    op.create_table('product_print_materials',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('material_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('additional_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['print_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'material_id', name='unique_product_material')
    )
    op.create_table('product_print_settings',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('settings_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('additional_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settings_id'], ['print_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'settings_id', name='unique_product_settings')
    )
    op.create_table('product_shipping_cities',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('city_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'city_id', name='unique_product_city')
    )
    op.create_table('product_translations',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.create_table('ratings',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('shipping_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED', 'FAILED', name='shippingstatusenum'), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    with op.batch_alter_table('shipping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_shipping_date'), ['shipping_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_tracking_number'), ['tracking_number'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('from_location_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('to_location_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'SALE', 'TRANSFER', 'RETURN', 'DAMAGE', 'LOSS', 'STOCK_ADJUSTMENT', 'EXPIRY', 'PROMOTION', 'INTERNAL_USE', 'VENDOR_RETURN', name='transactiontype'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('financial_year_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['branch.id'], name='fk_transaction_from_location_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['branch.id'], name='fk_transaction_to_location_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['fiscal_year.id'], name='fk_transaction_fiscal_year_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_transaction_product_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_financial_year_id'), ['financial_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_to_location_id'), ['to_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('print_job_logs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('print_job_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('status_from', sa.String(length=50), nullable=True),
    sa.Column('status_to', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_job_logs')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_product_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_from_location_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_financial_year_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_create_date'))

    op.drop_table('transaction')
    with op.batch_alter_table('shipping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_shipping_shipping_date'))

    op.drop_table('shipping')
    op.drop_table('ratings')
    op.drop_table('product_translations')
    op.drop_table('product_shipping_cities')
    op.drop_table('product_print_settings')
    op.drop_table('product_print_materials')
    op.drop_table('product_packaging_options')
    op.drop_table('product_cost_breakdown')
    op.drop_table('print_jobs')
    op.drop_table('order_items')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_create_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_branch_id'))

    op.drop_table('inventory')
    op.drop_table('slider_translations')
    op.drop_table('seller_performance')
    op.drop_table('seller_payments')
    op.drop_table('seller_documents')
    op.drop_table('seller_commissions')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_create_date'))
        batch_op.drop_index(batch_op.f('ix_product_code'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))

    op.drop_table('product')
    op.drop_table('printer_materials')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.drop_index(batch_op.f('ix_order_order_date'))
        batch_op.drop_index(batch_op.f('ix_order_create_date'))

    op.drop_table('order')
    op.drop_table('fiscal_period')
    op.drop_table('faq_translations')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_fiscal_year_id'))
        batch_op.drop_index(batch_op.f('ix_expense_create_date'))
        batch_op.drop_index(batch_op.f('ix_expense_category_id'))

    op.drop_table('expense')
    op.drop_table('customer_translations')
    op.drop_table('category_translations')
    op.drop_table('Item_translations')
    op.drop_table('user_roles')
    op.drop_table('templates_content_translations')
    op.drop_table('store_translations')
    with op.batch_alter_table('slider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slider_to_date'))
        batch_op.drop_index(batch_op.f('ix_slider_from_date'))

    op.drop_table('slider')
    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_addresses_create_date'))

    op.drop_table('shipping_addresses')
    op.drop_table('sellers')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    op.drop_table('printers')
    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_reference_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transaction_gateway_transaction_id'))

    op.drop_table('payment_transaction')
    with op.batch_alter_table('payment_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_config_name'))

    op.drop_table('payment_config')
    op.drop_table('login_tracking')
    op.drop_table('labor_category_translations')
    with op.batch_alter_table('labor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labor_create_date'))
        batch_op.drop_index(batch_op.f('ix_labor_code'))
        batch_op.drop_index(batch_op.f('ix_labor_category_id'))

    op.drop_table('labor')
    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_year_create_date'))

    op.drop_table('fiscal_year')
    op.drop_table('faq_topic_translations')
    op.drop_table('faq')
    op.drop_table('expense_category_translations')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_mobile'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_code'))
        batch_op.drop_index(batch_op.f('ix_customer_create_date'))

    op.drop_table('customer')
    op.drop_table('company_translations')
    op.drop_table('city_translations')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_slug'))
        batch_op.drop_index(batch_op.f('ix_category_create_date'))
        batch_op.drop_index(batch_op.f('ix_category_code'))

    op.drop_table('category')
    op.drop_table('cart_item')
    op.drop_table('branch_translations')
    op.drop_table('users')
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_notification_timestamp'))

    op.drop_table('user_notification')
    with op.batch_alter_table('templates_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_content_media_type'))
        batch_op.drop_index(batch_op.f('ix_templates_content_key'))

    op.drop_table('templates_content')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_supplier_email'))
        batch_op.drop_index(batch_op.f('ix_supplier_create_date'))

    op.drop_table('supplier')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_create_date'))

    op.drop_table('store')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_create_date'))

    op.drop_table('staff')
    op.drop_table('slider_type')
    op.drop_table('roles')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_number'))
        batch_op.drop_index(batch_op.f('ix_quotations_create_date'))

    op.drop_table('quotations')
    op.drop_table('product_packaging')
    op.drop_table('print_settings')
    op.drop_table('print_materials')
    op.drop_table('permissions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_create_date'))

    op.drop_table('payments')
    op.drop_table('payment_type')
    op.drop_table('payment_gateway')
    op.drop_table('media')
    op.drop_table('labor_category')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_create_date'))

    op.drop_table('invoices')
    op.drop_table('invoice_counter')
    op.drop_table('favorite')
    op.drop_table('faq_topic')
    op.drop_table('expense_category')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_create_date'))

    op.drop_table('company')
    op.drop_table('city')
    op.drop_table('cart')
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_create_date'))

    op.drop_table('branch')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
