"""migrate all indexes to model-based

Revision ID: b8dace70d8a8
Revises: add_admin_user
Create Date: 2025-10-22 17:42:08.083297

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8dace70d8a8'
down_revision = 'add_admin_user'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('idx_category_category_type', if_exists=True)
        batch_op.drop_index('idx_category_is_active', if_exists=True)
        batch_op.drop_index('idx_category_is_featured', if_exists=True)
        batch_op.drop_index('idx_category_parent_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_category_category_type'), ['category_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_parent_id'), ['parent_id'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('idx_customer_city', if_exists=True)
        batch_op.drop_index('idx_customer_country', if_exists=True)
        batch_op.drop_index('idx_customer_customer_type', if_exists=True)
        batch_op.drop_index('idx_customer_status', if_exists=True)
        batch_op.drop_index('idx_customer_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_customer_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_type'), ['customer_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index('idx_expense_amount', if_exists=True)
        batch_op.drop_index('idx_expense_date', if_exists=True)
        batch_op.drop_index('idx_expense_fiscal_year_id', if_exists=True)
        batch_op.drop_index('idx_expense_status', if_exists=True)
        batch_op.create_index(batch_op.f('ix_expense_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_status'), ['status'], unique=False)

    with op.batch_alter_table('fiscal_period', schema=None) as batch_op:
        batch_op.drop_index('idx_fiscal_period_end_date', if_exists=True)
        batch_op.drop_index('idx_fiscal_period_financial_year_id', if_exists=True)
        batch_op.drop_index('idx_fiscal_period_start_date', if_exists=True)
        batch_op.drop_index('idx_fiscal_period_status', if_exists=True)
        batch_op.create_index(batch_op.f('ix_fiscal_period_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_period_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_period_financial_year_id'), ['financial_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_period_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_period_status'), ['status'], unique=False)

    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.drop_index('idx_fiscal_year_company_id', if_exists=True)
        batch_op.drop_index('idx_fiscal_year_end_date', if_exists=True)
        batch_op.drop_index('idx_fiscal_year_start_date', if_exists=True)
        batch_op.drop_index('idx_fiscal_year_status', if_exists=True)
        batch_op.create_index(batch_op.f('ix_fiscal_year_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_status'), ['status'], unique=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_quantity', if_exists=True)
        batch_op.drop_index('idx_inventory_quantity_alert', if_exists=True)
        batch_op.create_index(batch_op.f('ix_inventory_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_quantity_alert'), ['quantity_alert'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('idx_invoices_branch_id', if_exists=True)
        batch_op.drop_index('idx_invoices_date', if_exists=True)
        batch_op.drop_index('idx_invoices_payment_status', if_exists=True)
        batch_op.drop_index('idx_invoices_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_invoices_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('idx_media_collection_name', if_exists=True)
        batch_op.drop_index('idx_media_model_id', if_exists=True)
        batch_op.drop_index('idx_media_model_type', if_exists=True)
        batch_op.create_index(batch_op.f('ix_media_collection_name'), ['collection_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_model_type'), ['model_type'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('idx_order_customer_id', if_exists=True)
        batch_op.drop_index('idx_order_estimated_completion', if_exists=True)
        batch_op.drop_index('idx_order_expected_delivery', if_exists=True)
        batch_op.drop_index('idx_order_order_type', if_exists=True)
        batch_op.drop_index('idx_order_payment_status', if_exists=True)
        batch_op.drop_index('idx_order_priority', if_exists=True)
        batch_op.drop_index('idx_order_status', if_exists=True)
        batch_op.drop_index('idx_order_supplier_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_estimated_completion'), ['estimated_completion'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_expected_delivery'), ['expected_delivery'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_order_items_material_id', if_exists=True)
        batch_op.drop_index('idx_order_items_order_id', if_exists=True)
        batch_op.drop_index('idx_order_items_product_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_order_items_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_transaction_amount', if_exists=True)
        batch_op.drop_index('idx_payment_transaction_is_online', if_exists=True)
        batch_op.drop_index('idx_payment_transaction_model_id', if_exists=True)
        batch_op.drop_index('idx_payment_transaction_model_type', if_exists=True)
        batch_op.drop_index('idx_payment_transaction_payment_status', if_exists=True)
        batch_op.drop_index('idx_payment_transaction_requester', if_exists=True)
        batch_op.create_index(batch_op.f('ix_payment_transaction_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_is_online'), ['is_online'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_model_type'), ['model_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_requester'), ['requester'], unique=False)

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_print_jobs_assigned_printer_id', if_exists=True)
        batch_op.drop_index('idx_print_jobs_material_id', if_exists=True)
        batch_op.drop_index('idx_print_jobs_order_id', if_exists=True)
        batch_op.drop_index('idx_print_jobs_status', if_exists=True)
        batch_op.drop_index('idx_print_jobs_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_print_jobs_assigned_printer_id'), ['assigned_printer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_index('idx_printers_branch_id', if_exists=True)
        batch_op.drop_index('idx_printers_is_active', if_exists=True)
        batch_op.drop_index('idx_printers_status', if_exists=True)
        batch_op.create_index(batch_op.f('ix_printers_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_printers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_printers_status'), ['status'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_product_base_price', if_exists=True)
        batch_op.drop_index('idx_product_category_id', if_exists=True)
        batch_op.drop_index('idx_product_currency', if_exists=True)
        batch_op.drop_index('idx_product_is_active', if_exists=True)
        batch_op.drop_index('idx_product_is_featured', if_exists=True)
        batch_op.drop_index('idx_product_product_type', if_exists=True)
        batch_op.drop_index('idx_product_subcategory_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_product_base_price'), ['base_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_type'), ['product_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_subcategory_id'), ['subcategory_id'], unique=False)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index('idx_quotations_branch_id', if_exists=True)
        batch_op.drop_index('idx_quotations_customer_id', if_exists=True)
        batch_op.drop_index('idx_quotations_qoute_status', if_exists=True)
        batch_op.drop_index('idx_quotations_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_quotations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_qoute_status'), ['qoute_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index('idx_ratings_product_id', if_exists=True)
        batch_op.drop_index('idx_ratings_score', if_exists=True)
        batch_op.drop_index('idx_ratings_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_ratings_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permissions_permission_id', if_exists=True)
        batch_op.drop_index('idx_role_permissions_role_id', if_exists=True)

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index('idx_sellers_is_active', if_exists=True)
        batch_op.drop_index('idx_sellers_status', if_exists=True)
        batch_op.drop_index('idx_sellers_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_sellers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sellers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sellers_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('shipping', schema=None) as batch_op:
        batch_op.drop_index('idx_shipping_order_id', if_exists=True)
        batch_op.drop_index('idx_shipping_status', if_exists=True)
        batch_op.create_index(batch_op.f('ix_shipping_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipping_status'), ['status'], unique=False)

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.drop_index('idx_shipping_addresses_city', if_exists=True)
        batch_op.drop_index('idx_shipping_addresses_country', if_exists=True)
        batch_op.drop_index('idx_shipping_addresses_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_shipping_addresses_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_addresses_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_addresses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index('idx_supplier_city', if_exists=True)
        batch_op.drop_index('idx_supplier_country', if_exists=True)
        batch_op.drop_index('idx_supplier_is_verified', if_exists=True)
        batch_op.drop_index('idx_supplier_status', if_exists=True)
        batch_op.create_index(batch_op.f('ix_supplier_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_status'), ['status'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('idx_transaction_from_location_id', if_exists=True)
        batch_op.drop_index('idx_transaction_to_location_id', if_exists=True)
        batch_op.drop_index('idx_transaction_transaction_type', if_exists=True)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_type'), ['transaction_type'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_roles_role_id', if_exists=True)
        batch_op.drop_index('idx_user_roles_user_id', if_exists=True)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_create_date', if_exists=True)
        batch_op.drop_index('idx_users_is_active', if_exists=True)
        batch_op.drop_index('idx_users_language', if_exists=True)
        batch_op.drop_index('idx_users_modified_date', if_exists=True)
        batch_op.drop_index('idx_users_user_type', if_exists=True)
        batch_op.create_index(batch_op.f('ix_users_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_modified_date'), ['modified_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_type'), ['user_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_users_modified_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_users_language'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_users_is_active'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_users_create_date'), if_exists=True)
        batch_op.create_index('idx_users_user_type', ['user_type'], unique=False)
        batch_op.create_index('idx_users_modified_date', ['modified_date'], unique=False)
        batch_op.create_index('idx_users_language', ['language'], unique=False)
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_create_date', ['create_date'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'), if_exists=True)
        batch_op.create_index('idx_user_roles_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_roles_role_id', ['role_id'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_type'), if_exists=True)
        batch_op.create_index('idx_transaction_transaction_type', ['transaction_type'], unique=False)
        batch_op.create_index('idx_transaction_to_location_id', ['to_location_id'], unique=False)
        batch_op.create_index('idx_transaction_from_location_id', ['from_location_id'], unique=False)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_supplier_is_verified'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_supplier_country'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_supplier_city'), if_exists=True)
        batch_op.create_index('idx_supplier_status', ['status'], unique=False)
        batch_op.create_index('idx_supplier_is_verified', ['is_verified'], unique=False)
        batch_op.create_index('idx_supplier_country', ['country'], unique=False)
        batch_op.create_index('idx_supplier_city', ['city'], unique=False)

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_addresses_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_shipping_addresses_country'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_shipping_addresses_city'), if_exists=True)
        batch_op.create_index('idx_shipping_addresses_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_shipping_addresses_country', ['country'], unique=False)
        batch_op.create_index('idx_shipping_addresses_city', ['city'], unique=False)

    with op.batch_alter_table('shipping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_shipping_order_id'), if_exists=True)
        batch_op.create_index('idx_shipping_status', ['status'], unique=False)
        batch_op.create_index('idx_shipping_order_id', ['order_id'], unique=False)

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sellers_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_sellers_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_sellers_is_active'), if_exists=True)
        batch_op.create_index('idx_sellers_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_sellers_status', ['status'], unique=False)
        batch_op.create_index('idx_sellers_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permissions_role_id', ['role_id'], unique=False)
        batch_op.create_index('idx_role_permissions_permission_id', ['permission_id'], unique=False)

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_ratings_score'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_ratings_product_id'), if_exists=True)
        batch_op.create_index('idx_ratings_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_ratings_score', ['score'], unique=False)
        batch_op.create_index('idx_ratings_product_id', ['product_id'], unique=False)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_quotations_qoute_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_quotations_customer_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_quotations_branch_id'), if_exists=True)
        batch_op.create_index('idx_quotations_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_quotations_qoute_status', ['qoute_status'], unique=False)
        batch_op.create_index('idx_quotations_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('idx_quotations_branch_id', ['branch_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_subcategory_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_product_product_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_product_is_featured'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_product_is_active'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_product_currency'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_product_base_price'), if_exists=True)
        batch_op.create_index('idx_product_subcategory_id', ['subcategory_id'], unique=False)
        batch_op.create_index('idx_product_product_type', ['product_type'], unique=False)
        batch_op.create_index('idx_product_is_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_product_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_product_currency', ['currency'], unique=False)
        batch_op.create_index('idx_product_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_product_base_price', ['base_price'], unique=False)

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printers_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_printers_is_active'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_printers_branch_id'), if_exists=True)
        batch_op.create_index('idx_printers_status', ['status'], unique=False)
        batch_op.create_index('idx_printers_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_printers_branch_id', ['branch_id'], unique=False)

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_jobs_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_print_jobs_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_print_jobs_order_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_print_jobs_material_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_print_jobs_assigned_printer_id'), if_exists=True)
        batch_op.create_index('idx_print_jobs_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_print_jobs_status', ['status'], unique=False)
        batch_op.create_index('idx_print_jobs_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_print_jobs_material_id', ['material_id'], unique=False)
        batch_op.create_index('idx_print_jobs_assigned_printer_id', ['assigned_printer_id'], unique=False)

    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_requester'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_payment_transaction_payment_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_payment_transaction_model_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_payment_transaction_model_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_payment_transaction_is_online'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_payment_transaction_amount'), if_exists=True)
        batch_op.create_index('idx_payment_transaction_requester', ['requester'], unique=False)
        batch_op.create_index('idx_payment_transaction_payment_status', ['payment_status'], unique=False)
        batch_op.create_index('idx_payment_transaction_model_type', ['model_type'], unique=False)
        batch_op.create_index('idx_payment_transaction_model_id', ['model_id'], unique=False)
        batch_op.create_index('idx_payment_transaction_is_online', ['is_online'], unique=False)
        batch_op.create_index('idx_payment_transaction_amount', ['amount'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_items_material_id'), if_exists=True)
        batch_op.create_index('idx_order_items_product_id', ['product_id'], unique=False)
        batch_op.create_index('idx_order_items_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_order_items_material_id', ['material_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_supplier_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_priority'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_payment_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_order_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_expected_delivery'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_estimated_completion'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_order_customer_id'), if_exists=True)
        batch_op.create_index('idx_order_supplier_id', ['supplier_id'], unique=False)
        batch_op.create_index('idx_order_status', ['status'], unique=False)
        batch_op.create_index('idx_order_priority', ['priority'], unique=False)
        batch_op.create_index('idx_order_payment_status', ['payment_status'], unique=False)
        batch_op.create_index('idx_order_order_type', ['order_type'], unique=False)
        batch_op.create_index('idx_order_expected_delivery', ['expected_delivery'], unique=False)
        batch_op.create_index('idx_order_estimated_completion', ['estimated_completion'], unique=False)
        batch_op.create_index('idx_order_customer_id', ['customer_id'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_model_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_media_model_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_media_collection_name'), if_exists=True)
        batch_op.create_index('idx_media_model_type', ['model_type'], unique=False)
        batch_op.create_index('idx_media_model_id', ['model_id'], unique=False)
        batch_op.create_index('idx_media_collection_name', ['collection_name'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_invoices_payment_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_invoices_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_invoices_branch_id'), if_exists=True)
        batch_op.create_index('idx_invoices_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_invoices_payment_status', ['payment_status'], unique=False)
        batch_op.create_index('idx_invoices_date', ['date'], unique=False)
        batch_op.create_index('idx_invoices_branch_id', ['branch_id'], unique=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_quantity_alert'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_inventory_quantity'), if_exists=True)
        batch_op.create_index('idx_inventory_quantity_alert', ['quantity_alert'], unique=False)
        batch_op.create_index('idx_inventory_quantity', ['quantity'], unique=False)

    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_year_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_fiscal_year_start_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_fiscal_year_end_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_fiscal_year_company_id'), if_exists=True)
        batch_op.create_index('idx_fiscal_year_status', ['status'], unique=False)
        batch_op.create_index('idx_fiscal_year_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_fiscal_year_end_date', ['end_date'], unique=False)
        batch_op.create_index('idx_fiscal_year_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('fiscal_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_period_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_fiscal_period_start_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_fiscal_period_financial_year_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_fiscal_period_end_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_fiscal_period_company_id'), if_exists=True)
        batch_op.create_index('idx_fiscal_period_status', ['status'], unique=False)
        batch_op.create_index('idx_fiscal_period_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_fiscal_period_financial_year_id', ['financial_year_id'], unique=False)
        batch_op.create_index('idx_fiscal_period_end_date', ['end_date'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_expense_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_expense_amount'), if_exists=True)
        batch_op.create_index('idx_expense_status', ['status'], unique=False)
        batch_op.create_index('idx_expense_fiscal_year_id', ['fiscal_year_id'], unique=False)
        batch_op.create_index('idx_expense_date', ['date'], unique=False)
        batch_op.create_index('idx_expense_amount', ['amount'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_customer_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_customer_customer_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_customer_country'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_customer_city'), if_exists=True)
        batch_op.create_index('idx_customer_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_customer_status', ['status'], unique=False)
        batch_op.create_index('idx_customer_customer_type', ['customer_type'], unique=False)
        batch_op.create_index('idx_customer_country', ['country'], unique=False)
        batch_op.create_index('idx_customer_city', ['city'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_parent_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_category_is_featured'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_category_is_active'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_category_category_type'), if_exists=True)
        batch_op.create_index('idx_category_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('idx_category_is_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_category_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_category_category_type', ['category_type'], unique=False)

    # ### end Alembic commands ###
