openapi: 3.0.1
info:
  title: Store3d API
  description: This is an Store3d API document
  contact:
    email: info@store3d.om
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://store3d-api.example.com/store3d/api/v1
- url: /store3d/api/v1
security:
- basicAuth: []
- JWT: []
tags:
- name: category
  description: Operations about Category

paths:
  /categories/:
    get:
      tags:
      - category
      summary: Get All Categories
      description: This can only be done by the logged in user.
      operationId: GetCategories
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
        401:
          $ref: '#/components/responses/Unauthorized'
    post:
      tags:
      - category
      summary: Create category
      description: This can only be done by the logged in user.
      operationId: CreateCategory
      requestBody:
        description: Create category object
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Store3dtCategory'
        required: true
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
  /categories/{id}:
    get:
      tags:
      - category
      summary: Get category
      description: This can only be done by the logged in user.
      operationId: getCategoryById
      parameters:
      - name: id
        in: path
        description: The id that needs to get
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    delete:
      tags:
      - category
      summary: Delete category
      description: This can only be done by the logged in user.
      operationId: delete_category
      parameters:
      - name: id
        in: path
        description: The id that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
    patch:
      tags:
      - category
      summary: Updated Category
      description: This can only be done by the logged in user.
      operationId: update_category
      parameters:
      - name: id
        in: path
        description: ID that need to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Updated category object
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Store3dtCategory'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Global'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
  /categories/dependencies/{parent_id}:
    get:
      tags:
      - category
      summary: Get category and its dependencies
      description: This can only be done by the logged in user.
      operationId: getCategoryDependenciesById
      parameters:
      - name: parent_id
        in: path
        description: The id that needs to get
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
                  dependencies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        401:
          $ref: '#/components/responses/Unauthorized'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        parent_id:
          type: string
          format: uuid
        form_id:
          type: string
          format: uuid
        order:
          type: integer
          format: int64
        enable:
          type: boolean
        css_class:
          type: string
        icon:
          type: string
          format: binary
        timestamp:
          type: string
          format: date-time
        name:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string
        content:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string
    Store3dtCategory:
      type: object
      properties:
        parent_id:
          type: string
          format: uuid
        form_id:
          type: string
          format: uuid
        order:
          type: integer
          format: int64
        enable:
          type: boolean
        css_class:
          type: string
        icon:
          type: string
          format: binary
        name:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string
        content:
          type: object
          properties:
            ar:
              type: string
            en:
              type: string

    Global:
      required:
      #- code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    Error:
      required:
      #- code
      - message
      type: object
      properties:
        #code:
        #  type: string
        message:
          type: string
          example: Authorization information is missing or invalid.
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    JWT:
      type: apiKey
      name: x-access-tokens
      in: header
